misc fixes
sjova/cypress-typescript-new-dib-playground pull request #43
Opened 2021-12-17 14:48 UTC by Nenad85

remove `wiatForAngular()` function form tests and small fixes

2021-12-20 11:33 UTC, stefannikolic approved these changes
Everything is okay.

2021-12-21 15:03 UTC, sjova commented on cypress/integration/dib-travel/company-settings/approval-process.spec.ts
> +  //TODO: This should be revisit after solving a problem with stripe.
Please follow right pattern for naming TODO

2021-12-21 15:03 UTC, sjova commented on cypress/integration/dib-travel/company-settings/approval-process.spec.ts
> +  xit('should check if selected traveler group already has approval process', () => {
We shouldn't use `xit`. Please comment out the whole block instead.

2021-12-21 15:03 UTC, sjova commented on cypress/integration/dib-travel/company-settings/approval-process.spec.ts
> +  xit('should delete approval process for traveler group (this overrides any travel policy)', () => {
Same as above

2021-12-21 15:03 UTC, sjova commented on cypress/integration/dib-travel/company-settings/subscription.spec.ts
> +  /*after(() => {
Please revert this. We should keep this logic separated from the test itself.

2021-12-21 15:03 UTC, sjova commented on cypress/integration/dib-travel/company-settings/subscription.spec.ts
> +  //TODO: This should be revisit after solving a problems with stripe.
Same as above.

2021-12-21 15:03 UTC, sjova commented on cypress/integration/dib-travel/company-settings/subscription.spec.ts
> +  xit('should buy new license for subscription', () => {
Same as above.

2021-12-21 15:03 UTC, sjova commented on cypress/integration/dib-travel/company-settings/subscription.spec.ts
> +    cy.visit('/people-management/groups');
See the above comment related to this. This logic should stay separated

2021-12-21 21:13 UTC, sjova requested changes
We should resolve all suggestions before the merge.

2021-12-23 13:48 UTC, sjova approved these changes

2021-12-23 13:48 UTC, merged