Misc fixes
sjova/cypress-typescript-new-dib-playground pull request #51
Opened 2022-01-19 08:33 UTC by Nenad85

misc fixes

2022-01-19 13:34 UTC, sjova commented on cypress/integration/dib-travel/company-settings/subscription/helpers/confirmation-displaying-first-page.ts
> +  cy.get('dib-company-management dib-subscription dib-subscription-purchase-history p').should('contain', date);
This one-liner is not a huge benefit.

You can use `cy.get('dib-company-management dib-subscription dib-subscription-purchase-history p').should('contain', date);` directly

2022-01-19 13:34 UTC, sjova commented on cypress/integration/dib-travel/company-settings/subscription.spec.ts
> +    // TODO: This should be discussed, because on the staging environment, we don't have section "INVOICE RECIPIENT E-MAIL AND VAT NUMBER"
maybe you can add env if/else here? And staging can be clarified later

2022-01-19 13:34 UTC, sjova commented on cypress/integration/dib-travel/company-settings/payment-method/billing-profiles.spec.ts
> +    // TODO: This should be discussed, because on the staging environment, we don't have section "INVOICE RECIPIENT E-MAIL AND VAT NUMBER"
Same as on other place

2022-01-19 13:34 UTC, sjova commented on cypress/integration/dib-travel/company-settings/payment-method/billing-profiles.spec.ts
> +    // TODO: This should be discussed, because on the staging environment, we don't have section "INVOICE RECIPIENT E-MAIL AND VAT NUMBER"
Same as other place

2022-01-19 13:34 UTC, sjova commented on cypress/integration/dib-travel-iframe/company-settings/payment-method/helpers/submit-empty-credit-card-form-and-confirm.ts
> +    // TODO: This should be discussed, because on the staging environment, we don't have section "COMPANY INFORMATION"
Same as other places.

2022-01-19 15:19 UTC, sjova requested changes
ping me when you implement all fixes

2022-01-20 08:18 UTC, sjova approved these changes
Feel free to merge after @stefannikolic approval

2022-01-20 09:09 UTC, stefannikolic approved these changes
Everything is okay.

2022-01-20 09:10 UTC, merged